remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: https://github.com/choice-career/jp-holiday
      title: 開発リポジトリ
